# .github/workflows/update-portfolio-data.yml
name: Update Portfolio Data

on:
  # Run every 6 hours
  schedule:
    - cron: "0 0 * * 0"

  # Run on push to main branch
  push:
    branches: [main]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Fetch GitHub data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          node scripts/fetch-github-data.js

      - name: Commit and push if data changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/portfolio.json
          git diff --staged --quiet || git commit -m "Update portfolio data [skip ci]"
          git push
